// <auto-generated />
using System;
using Infrustracher;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrustracher.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Admissions", b =>
                {
                    b.Property<int>("admissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admissionId"));

                    b.Property<DateTime>("admissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("bedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("admissionId");

                    b.HasIndex("bedId");

                    b.HasIndex("doctorId");

                    b.HasIndex("patientId");

                    b.HasIndex("roomId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("Domain.Appointments", b =>
                {
                    b.Property<int>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointmentId"));

                    b.Property<DateTime>("appointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("appointmentId");

                    b.HasIndex("departmentId");

                    b.HasIndex("doctorId");

                    b.HasIndex("patientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Domain.Beds", b =>
                {
                    b.Property<int>("bedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bedId"));

                    b.Property<string>("bedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("bedId");

                    b.HasIndex("roomId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Domain.Bills", b =>
                {
                    b.Property<int>("billId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("billId"));

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<bool>("paymentStatus")
                        .HasColumnType("bit");

                    b.Property<double>("totalAmount")
                        .HasColumnType("float");

                    b.HasKey("billId");

                    b.HasIndex("patientId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Domain.BillsItems", b =>
                {
                    b.Property<int>("billItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("billItemId"));

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int>("billId")
                        .HasColumnType("int");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("billItemId");

                    b.HasIndex("billId");

                    b.ToTable("BillsItems");
                });

            modelBuilder.Entity("Domain.Departments", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Doctors", b =>
                {
                    b.Property<int>("doctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctorId"));

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<double>("fees")
                        .HasColumnType("float");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("doctorId");

                    b.HasIndex("departmentId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Domain.LabTests", b =>
                {
                    b.Property<int>("labTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("labTestId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("testName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("labTestId");

                    b.HasIndex("doctorId");

                    b.HasIndex("patientId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("Domain.MedicalRecords", b =>
                {
                    b.Property<int>("medicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("medicalRecordId"));

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<string>("symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("visitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("medicalRecordId");

                    b.HasIndex("doctorId");

                    b.HasIndex("patientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Domain.Medicines", b =>
                {
                    b.Property<int>("medicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("medicineId"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("expirationDate")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<int>("supplierId")
                        .HasColumnType("int");

                    b.HasKey("medicineId");

                    b.HasIndex("supplierId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Domain.Patients", b =>
                {
                    b.Property<int>("patientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientId"));

                    b.Property<string>("addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("emergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("patientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Domain.PrescriptionItems", b =>
                {
                    b.Property<int>("prescriptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prescriptionItemId"));

                    b.Property<string>("dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("medicineId")
                        .HasColumnType("int");

                    b.Property<int>("prescriptionId")
                        .HasColumnType("int");

                    b.HasKey("prescriptionItemId");

                    b.HasIndex("medicineId");

                    b.HasIndex("prescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("Domain.Prescriptions", b =>
                {
                    b.Property<int>("prescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prescriptionId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("medicalRecordId")
                        .HasColumnType("int");

                    b.HasKey("prescriptionId");

                    b.HasIndex("medicalRecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Domain.Rooms", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roomId"));

                    b.Property<double>("chargePerDay")
                        .HasColumnType("float");

                    b.Property<string>("roomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.Suppliers", b =>
                {
                    b.Property<int>("supplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supplierId"));

                    b.Property<string>("contactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("supplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Domain.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Admissions", b =>
                {
                    b.HasOne("Domain.Beds", "bed")
                        .WithMany("admissions")
                        .HasForeignKey("bedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Doctors", "doctor")
                        .WithMany("admissions")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Patients", "patient")
                        .WithMany("admissions")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Rooms", "room")
                        .WithMany("admissions")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("bed");

                    b.Navigation("doctor");

                    b.Navigation("patient");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Appointments", b =>
                {
                    b.HasOne("Domain.Departments", "department")
                        .WithMany("appointments")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Doctors", "doctor")
                        .WithMany("appointments")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Patients", "patient")
                        .WithMany("appointments")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Beds", b =>
                {
                    b.HasOne("Domain.Rooms", "room")
                        .WithMany("beds")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Bills", b =>
                {
                    b.HasOne("Domain.Patients", "patient")
                        .WithMany("bills")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.BillsItems", b =>
                {
                    b.HasOne("Domain.Bills", "bill")
                        .WithMany("billItems")
                        .HasForeignKey("billId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bill");
                });

            modelBuilder.Entity("Domain.Doctors", b =>
                {
                    b.HasOne("Domain.Departments", "department")
                        .WithMany()
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users", "user")
                        .WithOne()
                        .HasForeignKey("Domain.Doctors", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.LabTests", b =>
                {
                    b.HasOne("Domain.Doctors", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Patients", "patient")
                        .WithMany("labTests")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.MedicalRecords", b =>
                {
                    b.HasOne("Domain.Doctors", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Patients", "patient")
                        .WithMany("medicalRecords")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Medicines", b =>
                {
                    b.HasOne("Domain.Suppliers", "supplier")
                        .WithMany("medicines")
                        .HasForeignKey("supplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("Domain.PrescriptionItems", b =>
                {
                    b.HasOne("Domain.Medicines", "medicine")
                        .WithMany()
                        .HasForeignKey("medicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Prescriptions", "prescription")
                        .WithMany("prescriptionItems")
                        .HasForeignKey("prescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicine");

                    b.Navigation("prescription");
                });

            modelBuilder.Entity("Domain.Prescriptions", b =>
                {
                    b.HasOne("Domain.MedicalRecords", "medicalRecord")
                        .WithMany("prescriptions")
                        .HasForeignKey("medicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicalRecord");
                });

            modelBuilder.Entity("Domain.Beds", b =>
                {
                    b.Navigation("admissions");
                });

            modelBuilder.Entity("Domain.Bills", b =>
                {
                    b.Navigation("billItems");
                });

            modelBuilder.Entity("Domain.Departments", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("Domain.Doctors", b =>
                {
                    b.Navigation("admissions");

                    b.Navigation("appointments");
                });

            modelBuilder.Entity("Domain.MedicalRecords", b =>
                {
                    b.Navigation("prescriptions");
                });

            modelBuilder.Entity("Domain.Patients", b =>
                {
                    b.Navigation("admissions");

                    b.Navigation("appointments");

                    b.Navigation("bills");

                    b.Navigation("labTests");

                    b.Navigation("medicalRecords");
                });

            modelBuilder.Entity("Domain.Prescriptions", b =>
                {
                    b.Navigation("prescriptionItems");
                });

            modelBuilder.Entity("Domain.Rooms", b =>
                {
                    b.Navigation("admissions");

                    b.Navigation("beds");
                });

            modelBuilder.Entity("Domain.Suppliers", b =>
                {
                    b.Navigation("medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
